const names = require('./4_names')
const sayHi = require('./5_utils')
//console.log(names)

const data = require('./6_alternative_flavor')
require('./7_mind_grenade')
// console.log(data)
// sayHi('susan')
// sayHi(names.john)
// sayHi(names.peter)